#!/usr/bin/env php
<?php

use RocketLab\Bundle\App\Libs\Kernel;
use RocketLab\Bundle\App\Libs\Loader\AdvancedLoader;
use RocketLab\Bundle\App\Libs\Rails;

require __DIR__ . '/vendor/autoload.php';
$_ENV['APP_ENV'] = 'test';
PhpLab\Core\Libs\Env\DotEnvHelper::init(__DIR__);
$_ENV['PROJECT_DIR'] = realpath(__DIR__);
$_ENV['APP_DIR'] = realpath(__DIR__ . '/console');
$_ENV['APP_NAME'] = 'console';

$loader = new AdvancedLoader($_ENV);
$kernel = new Kernel($_ENV, $loader);
$mainConfig = $kernel->run();
Rails::initAll($_ENV['PROJECT_DIR']);

$application = new yii\console\Application($mainConfig);
$exitCode = $application->run();
exit($exitCode);
